motor:
  - r_name: "r_shoulder_pitch"
    l_name: "l_shoulder_pitch"
    l_limit: -1.5
    u_limit: 1.5

  - r_name: "r_elbow"
    l_name: "l_elbow"
    l_limit: -1.55
    u_limit: 1.25

  - r_name: "r_hip_pitch"
    l_name: "l_hip_pitch"
    l_limit: -1.7
    u_limit: 0.45

  - r_name: "r_knee"
    l_name: "l_knee"
    l_limit: -0.05
    u_limit: 2.2

  - r_name: "r_ankle_pitch"
    l_name: "l_ankle_pitch"
    l_limit: -1.2
    u_limit: 1.35

sensor:
  - name: "imu_gyro"
    l_limit: -5.0
    u_limit: 5.0
    
  - name: "torso"
    l_limit: -3.14
    u_limit: 3.14

position:
  - name: "robot_position"
